server:
  port: 8081

management:
  security:
    enabled: false

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest